version: "3.5"

services:
  pgsql-master:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - "./sql/master.sql:/docker-entrypoint-initdb.d/master.sql"
    links:
      - pgsql-slave1
      - pgsql-slave2
    ports:
      - "5432:5432"

  pgsql-slave1:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - "./sql/shard1.sql:/docker-entrypoint-initdb.d/shard1.sql"
    ports:
      - "5433:5432"

  pgsql-slave2:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - "./sql/shard2.sql:/docker-entrypoint-initdb.d/shard2.sql"
    ports:
      - "5434:5432"

  adminer:
    image: adminer
    restart: always
    links:
      - pgsql-slave1
      - pgsql-slave2
      - pgsql-master
    ports:
      - "8080:8080"

  php:
    image: hw21-php
    build:
      context: .
      dockerfile: phpDockerFile
    restart: always
    depends_on:
      - pgsql-master
    links:
      - pgsql-master
    volumes:
      - "./etc:/var/www/html/public"